export const IMGCharacter = [
    {
        id: 0,
        URLImageButton: 'images/button/Nakoruru.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg',     
    },
    {
        id: 1,
        URLImageButton: 'images/button/Haohmaru.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg',
    },
    {
        id: 2,
        URLImageButton: 'images/button/Ukyo.png',
        // URLImageSoul: 'images/Ukyo_Tachibana/HL.jpg',
        // URLImageSoul_1: 'images/Ukyo_Tachibana/HC.jpg',
        // URLImageSoul_2: 'images/Ukyo_Tachibana/HC_1.jpg',
        // URLImageSoul_3: 'images/Ukyo_Tachibana/HD.jpg',
        // URLWeapon: 'images/Ukyo_Tachibana/HVK.jpg',
        // URLTome: 'images/Ukyo_Tachibana/HS.jpg',
        // URLBadge: 'images/Ukyo_Tachibana/HH.jpg',
        // URLSkill: 'images/Ukyo_Tachibana/SKILL_1.jpg',
        // URLSkill_1: 'images/Ukyo_Tachibana/SKILL_2.jpg',
        // URLPassiveSkill: 'images/Ukyo_Tachibana/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/Ukyo_Tachibana/NOITAI_2.jpg',
        // URLFate_1: 'images/Ukyo_Tachibana/DN_1.jpg',
        // URLFate_2: 'images/Ukyo_Tachibana/DN_2.jpg',
        // URLFate_3: 'images/Ukyo_Tachibana/DN_3.jpg',
    },
    {
        id: 3,
        URLImageButton: 'images/button/Heavy_D.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg',
    },
    {
        id: 4,
        URLImageButton: 'images/button/Lucky.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg',
    },
    {
        id: 5,
        URLImageButton: 'images/button/Brian.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 6,
        URLImageButton: 'images/button/Kyo_Kusanagi.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 7,
        URLImageButton: 'images/button/Benimaru.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 8,
        URLImageButton: 'images/button/Daimon.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 9,
        URLImageButton: 'images/button/Kyo_NEST.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 10,
        URLImageButton: 'images/button/Benimaru_2003.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 11,
        URLImageButton: 'images/button/Hidden_Person.png',
    },
    {
        id: 12,
        URLImageButton: 'images/button/Athena.png',
        // URLImageSoul: 'images/bear/HL.jpg',
        // URLImageSoul_1: 'images/bear/HC.jpg',
        // URLImageSoul_2: 'images/bear/HC_1.jpg',
        // URLImageSoul_3: 'images/bear/HD.jpg',
        // URLWeapon: 'images/bear/HVK.jpg',
        // URLTome: 'images/bear/HS.jpg',
        // URLBadge: 'images/bear/HH.jpg',
        // URLSkill: 'images/bear/SKILL_1.jpg',
        // URLSkill_1: 'images/bear/SKILL_2.jpg',
        // URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        // URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        // URLFate_1: 'images/bear/DN_1.jpg',
        // URLFate_2: 'images/bear/DN_2.jpg',
        // URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 13,
        URLImageButton: 'images/button/Kensou.png',
    },
    {
        id: 14,
        URLImageButton: 'images/button/Chin.png',
    },
    {
        id: 15,
        URLImageButton: 'images/button/Athena_2002.png',
    },
    {
        id: 16,
        URLImageButton: 'images/button/Kensou_III.png',
    },
    {
        id: 17,
        URLImageButton: 'images/button/Chizuru.png',
    },
    {
        id: 18,
        URLImageButton: 'images/button/Mai.png',
    },
    {
        id: 19,
        URLImageButton: 'images/button/King.png',
    },
    {
        id: 20,
        URLImageButton: 'images/button/Maki.png',
    },
    {
        id: 21,
        URLImageButton: 'images/button/Alluring_Mai.png',
    },
    {
        id: 22,
        URLImageButton: 'images/button/Hidden_Person.png',
    },
    {
        id: 23,
        URLImageButton: 'images/button/Iori.png',
    },
    {
        id: 24,
        URLImageButton: 'images/button/Mature.png',
    },
    {
        id: 25,
        URLImageButton: 'images/button/Vice.png',
    },
    {
        id: 26,
        URLImageButton: 'images/button/Iori_Crazy.png',
    },
    {
        id: 27,
        URLImageButton: 'images/button/Mature.png',
    },
    {
        id: 28,
        URLImageButton: 'images/button/Vice.png',
    },
    {
        id: 29,
        URLImageButton: 'images/button/Chris.png',
    },
    {
        id: 30,
        URLImageButton: 'images/button/Yashiro.png',
    },
    {
        id: 31,
        URLImageButton: 'images/button/Shermie.png',
    },



    
    

]

