export const IMGCharacter = [
    {
        id: 0,
        URLImageButton: 'images/button/Nakoruru.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg',     
    },
    {
        id: 1,
        URLImageButton: 'images/button/Haohmaru.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg',
    },
    {
        id: 2,
        URLImageButton: 'images/button/Ukyo.png',
        URLImageSoul: 'images/Ukyo_Tachibana/HL.jpg',
        URLImageSoul_1: 'images/Ukyo_Tachibana/HC.jpg',
        URLImageSoul_2: 'images/Ukyo_Tachibana/HC_1.jpg',
        URLImageSoul_3: 'images/Ukyo_Tachibana/HD.jpg',
        URLWeapon: 'images/Ukyo_Tachibana/HVK.jpg',
        URLTome: 'images/Ukyo_Tachibana/HS.jpg',
        URLBadge: 'images/Ukyo_Tachibana/HH.jpg',
        URLSkill: 'images/Ukyo_Tachibana/SKILL_1.jpg',
        URLSkill_1: 'images/Ukyo_Tachibana/SKILL_2.jpg',
        URLPassiveSkill: 'images/Ukyo_Tachibana/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/Ukyo_Tachibana/NOITAI_2.jpg',
        URLFate_1: 'images/Ukyo_Tachibana/DN_1.jpg',
        URLFate_2: 'images/Ukyo_Tachibana/DN_2.jpg',
        URLFate_3: 'images/Ukyo_Tachibana/DN_3.jpg',
    },
    {
        id: 3,
        URLImageButton: 'images/button/Heavy_D.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg',
    },
    {
        id: 4,
        URLImageButton: 'images/button/Lucky.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg',
    },
    {
        id: 5,
        URLImageButton: 'images/button/Brian.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 6,
        URLImageButton: 'images/button/Kyo_Kusanagi.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 7,
        URLImageButton: 'images/button/Benimaru.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 8,
        URLImageButton: 'images/button/Daimon.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 9,
        URLImageButton: 'images/button/Kyo_NEST.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg'
    },
    {
        id: 10,
        URLImageButton: 'images/button/Benimaru_2003.png',
        URLImageSoul: 'images/bear/HL.jpg',
        URLImageSoul_1: 'images/bear/HC.jpg',
        URLImageSoul_2: 'images/bear/HC_1.jpg',
        URLImageSoul_3: 'images/bear/HD.jpg',
        URLWeapon: 'images/bear/HVK.jpg',
        URLTome: 'images/bear/HS.jpg',
        URLBadge: 'images/bear/HH.jpg',
        URLSkill: 'images/bear/SKILL_1.jpg',
        URLSkill_1: 'images/bear/SKILL_2.jpg',
        URLPassiveSkill: 'images/bear/NOITAI_1.jpg',
        URLPassiveSkill_2: 'images/bear/NOITAI_2.jpg',
        URLFate_1: 'images/bear/DN_1.jpg',
        URLFate_2: 'images/bear/DN_2.jpg',
        URLFate_3: 'images/bear/DN_3.jpg'
    },
]

